"""initial migration

Revision ID: 2a702e5f5b0e
Revises: 1619d6a34c95
Create Date: 2025-05-05 16:25:04.381294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a702e5f5b0e'
down_revision: Union[str, None] = '1619d6a34c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'column_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'column_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
