"""prueba

Revision ID: 93540ea37e3a
Revises: 2a702e5f5b0e
Create Date: 2025-05-06 02:20:18.706352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93540ea37e3a'
down_revision: Union[str, None] = '2a702e5f5b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'column_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('column_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
